### ISSUE TITLE
Kyoto.js 11 KPT

### ISSUE THREAD

**Issue by fand** [kyotojs/meetup#1]
やっていく

**Comment by fand** [comment]
# K
- 前日に会場設営しててよかった
  - 社内でTODOリストつくってた
- BGMよかった
- 会場案内スライド作っておいてよかった
- 開始即乾杯

# P
- 初参加の人々と話しそびれた 🙀🙀🙀
  - 一番問題な気がする
  - 名札ほしい
- 誰が出席したのかわからない
- 時代祭にぶつかった
  - 調整さんつくる時に京都カレンダーをチェックする
- はてなへの依存度が高い（なんとなく）
  - はてな社員に手伝って頂いた、ありがとうございます
  - コアメンバーというわけでもなさそう？
  - 社員がもうちょい発表するといいのかな

# T
- 受付ちゃんとする
  - 出席確認
  - 名札わたす
  - 飲み物わたす
- 開催頻度を高くしたい
  - 調整さんつくるぞ
- 参加費を徴収する？
- 動画配信したい！

**Comment by takuyaa** [comment]
## K
- 発表枠わりとシュッと埋まった
  - 内容も多様性があった
- 懇親会盛り上がってた

## P
- ほとんど amagi くん一人で準備してて大変そうだった
  - 当日も買い出しとか司会とかもろもろ
- 発表したりしないと認識してもらえない問題
  - それはお互いにそうで、話しかけるきっかけが難しい
  - もっとトピックが狭い勉強会だと話しやすい
  - Elasticsearch 勉強会だと、業務で Es 使ってるんですか？とか聞ける

## T
- とりあえずはてな社内でもうちょっとスタッフやるひと増やしたい
- 名札つけるのいいと思った、あと自己紹介も書いてあるといいかも？

**Comment by bouzuya** [comment]
> K: BGMよかった
> P: 時代祭にぶつかった 

謎 BGM もよかった

> 参加費を徴収する？

ぼくは平気ですよ

> ほとんど amagi くん一人で準備してて大変そうだった 

わかる

> もっとトピックが狭い勉強会だと話しやすい

諸刃

**Comment by fand** [comment]
皆様有難うございました！
